version: '3'
services:
  nginx:
    build: .
    ports:
     - "8083:80"
    volumes:
     - type: bind
       source: ~/projects/simple-nginx/config/default.conf
       target: /etc/nginx/conf.d/default.conf
       read_only: true
