version: '3'
services:
  nginx:
    build: ./nginx
    ports:
     - "8083:80"
    volumes:
     - "/home/ant/projects/simple-nginx/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"

  joke-web:
    build: ./joke-web
    ports:
     - "8081:8080"

  career-web:
    build: ./career-web
    ports:
     - "8082:8080"
