version: '3'
services:
  nginx:
    build: ./nginx
    ports:
     - "8080:80"
    volumes:
     - "./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
  jokehub:
    build: ./jokehub
    volumes:
      - ${BUILD_TARGET}/${JAR_JOKEHUB}:/app.jar
    ports:
     - "8081:8080"

  career-web:
    build: ./career-web
    ports:
     - "8082:8080"

  # ghost:
  #   build: ./ghost
  #   ports:
  #    - "8083:2368"
